version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
      #- pytest
artifacts:
  files:
    - '**/*'
  base-directory: movies