version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip3 install -r requirements.txt -t ./src

  build:
    commands:
      #- pytest
artifacts:
  type: zip
  files:
    - '**/*'
